from __future__ import annotations

import hashlib
import json
import sqlite3
import tempfile
import unittest
from pathlib import Path

from phase_tracker.archive_files import sha256_file
from phase_tracker.domain import Agent, Coordinate, WorkflowState
from phase_tracker.state_store import StateStore
from phase_tracker.workbench import (
    ResearchWorkbenchService,
    WorkbenchAttachmentService,
    WorkflowReference,
)
from phase_tracker.workbench.store import WorkbenchStore


class ResearchWorkbenchVerticalSliceTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.version = self.root / "p5" / "p5-b3" / "p5-b3-v12"
        self.version.mkdir(parents=True)
        self.proof = self.version / "proof.md"
        self.proof.write_text(
            "The heliotropic covenant requires a parity witness.\n",
            encoding="utf-8",
        )
        self.notes = self.version / "notes.txt"
        self.notes.write_text(
            "Internal note: compare the two explicit constructions.\n",
            encoding="utf-8",
        )
        self.unselected = self.version / "unselected.txt"
        self.unselected.write_text("This must not enter the run.\n", encoding="utf-8")
        coordinate = Coordinate(5, 3, 12, "p5")
        self.initial_state = WorkflowState(
            active_agent=Agent.AUDITOR,
            auditor_revision=True,
            last_coordinate=coordinate,
        )
        self.state_store = StateStore(self.root)
        self.state_store.save(self.initial_state)
        self.state_before = self.state_store.state_path.read_bytes()
        self.events_before = self._optional_bytes(self.state_store.events_path)

    def _create_run(self):
        return ResearchWorkbenchService(self.root).create_campaign_run(
            "Establish the exact evidence for the parity witness.",
            "p5/p5-b3/p5-b3-v12/proof.md",
            (self.proof, self.notes),
        )

    def _assert_workflow_unchanged(self) -> None:
        self.assertEqual(self.state_store.state_path.read_bytes(), self.state_before)
        self.assertEqual(
            self._optional_bytes(self.state_store.events_path),
            self.events_before,
        )
        self.assertEqual(
            self.state_store.load().to_dict(),
            self.initial_state.to_dict(),
        )
        branches = self.root / "p5" / "p5-b3"
        self.assertEqual(
            sorted(path.name for path in branches.iterdir() if path.is_dir()),
            ["p5-b3-v12"],
        )

    @staticmethod
    def _optional_bytes(path: Path) -> bytes | None:
        return path.read_bytes() if path.exists() else None

    def test_run_is_hashed_internal_only_and_workflow_read_only(self) -> None:
        receipt = self._create_run()
        self._assert_workflow_unchanged()

        summary_object = self.root / receipt.summary_object_path
        self.assertEqual(sha256_file(summary_object), receipt.summary_sha256)
        self.assertIn("USER RESEARCH · CREATED · NOT PROVIDED", receipt.summary_text)
        self.assertIn("Generated by the user Research Workbench.", receipt.summary_text)
        self.assertIn("Not provided to any agent", receipt.summary_text)
        self.assertNotIn("This must not enter the run", receipt.summary_text)

        manifest_path = self.root / receipt.run_manifest_path
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.assertEqual(set(manifest), {
            "run_id",
            "campaign_id",
            "project_id",
            "created_by",
            "created_at",
            "completed_at",
            "status",
            "supersedes_run_id",
            "plan",
            "policies",
            "artifacts",
            "pipeline_authority",
            "manifest_hash",
        })
        self.assertTrue(manifest["run_id"].startswith("rr_"))
        self.assertEqual(manifest["created_by"], "user")
        self.assertEqual(manifest["pipeline_authority"], "none")
        self.assertEqual(manifest["plan"]["mode"], "internal_only")
        self.assertEqual(
            manifest["plan"]["selected_artifacts"],
            [
                "p5/p5-b3/p5-b3-v12/notes.txt",
                "p5/p5-b3/p5-b3-v12/proof.md",
            ],
        )
        stored_hash = manifest["manifest_hash"]
        manifest["manifest_hash"] = None
        canonical = json.dumps(
            manifest,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
        self.assertEqual(hashlib.sha256(canonical).hexdigest(), stored_hash)

        provenance_path = self.root / receipt.provenance_path
        provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
        self.assertTrue(provenance["states"]["created"])
        for state in (
            "attached",
            "provided_to_agent",
            "acknowledged_by_agent",
            "relied_on_by_agent",
            "audited",
            "adopted",
            "published",
        ):
            self.assertFalse(provenance["states"][state], state)
        self.assertEqual(
            provenance["agent_delivery"],
            {
                "operator": "not_provided",
                "guardian": "not_provided",
                "auditor": "not_provided",
            },
        )
        self.assertEqual(WorkbenchStore(self.root).exposure_event_count(), 0)

        connection = sqlite3.connect(WorkbenchStore(self.root).db_path)
        try:
            with self.assertRaises(sqlite3.IntegrityError):
                connection.execute(
                    "UPDATE runs SET status = 'failed' WHERE run_id = ?",
                    (receipt.run_id,),
                )
        finally:
            connection.close()

    def test_attachment_is_chronology_not_delivery(self) -> None:
        run = self._create_run()
        reference = WorkflowReference(5, 3, 12, "p5")
        receipt = WorkbenchAttachmentService(self.root).attach(
            run,
            reference,
            "Recorded while revising the Auditor response.",
        )
        self._assert_workflow_unchanged()

        self.assertEqual(receipt.destination.parent.name, "user-research")
        self.assertEqual(
            sorted(path.name for path in receipt.destination.iterdir()),
            ["artifact-links.json", "provenance.json", "summary.md"],
        )
        self.assertEqual(
            sha256_file(receipt.destination / "summary.md"),
            run.summary_sha256,
        )
        provenance = json.loads(
            (receipt.destination / "provenance.json").read_text(encoding="utf-8")
        )
        self.assertEqual(set(provenance), {
            "attachment_id",
            "project_id",
            "workflow_position",
            "artifact_id",
            "artifact_sha256",
            "attached_by",
            "attached_at",
            "origin_label",
            "pipeline_authority",
            "agent_delivery",
            "note",
        })
        self.assertTrue(provenance["attachment_id"].startswith("wa_"))
        self.assertEqual(provenance["attached_by"], "user")
        self.assertEqual(provenance["origin_label"], "user_research_workbench")
        self.assertEqual(provenance["pipeline_authority"], "none")
        self.assertEqual(
            provenance["agent_delivery"],
            {
                "operator": "not_provided",
                "guardian": "not_provided",
                "auditor": "not_provided",
            },
        )
        self.assertEqual(provenance["workflow_position"], {
            "phase": 5,
            "branch": 3,
            "version": 12,
        })
        self.assertEqual(WorkbenchStore(self.root).exposure_event_count(), 0)

        connection = sqlite3.connect(WorkbenchStore(self.root).db_path)
        try:
            counts = connection.execute(
                "SELECT "
                "(SELECT COUNT(*) FROM campaigns), "
                "(SELECT COUNT(*) FROM runs), "
                "(SELECT COUNT(*) FROM attachments), "
                "(SELECT COUNT(*) FROM exposure_events)"
            ).fetchone()
        finally:
            connection.close()
        self.assertEqual(counts, (1, 1, 1, 0))

if __name__ == "__main__":
    unittest.main()
